language: php

php:
  - 7.0
  - 7.1
  - 7.2

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

sudo: required
addons:
  chrome: stable

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer update ${COMPOSER_OPTS}

script:
  - bash .travis/runTests.bash
