language: php

php:
  - 7.0

sudo: required
addons:
  chrome: stable

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer update ${COMPOSER_OPTS}

script:
  - bash shellscripts/runTests.bash
