language: php

sudo: required
addons:
  chrome: stable
  apt:
    packages:
      - unzip
      - chromedriver

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer update ${COMPOSER_OPTS}

script:
  - bash shellscripts/runTests.bash
