language: php

php:
  - 7.0

sudo: required
addons:
  chrome: stable

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer update ${COMPOSER_OPTS}
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - sudo unzip chromedriver_linux64.zip -d /usr/local/bin/

script:
  - bash shellscripts/runTests.bash
